# Site settings
title: PACKMAN
email: dongli@lasg.iap.ac.cn
description: > # this means to ignore newlines until "baseurl:"
  This is the home site of PACKMAN. PACKMAN is a cross-platform package
  manager written in Ruby.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  dongli

# Build settings
markdown: kramdown